"""
Django settings for mynewsite project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import socket

# Get environment for production settings
def get_env_bool(key, default=False):
    """Get boolean from environment variable"""
    val = os.environ.get(key, '').lower()
    if val in ('true', '1', 'yes'):
        return True
    elif val in ('false', '0', 'no'):
        return False
    return default

# Production detection
IS_PRODUCTION = os.environ.get('DJANGO_ENV') == 'production'


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECURITY: Use environment variable in production
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-gf7l^42ba)oc=rvv87_ocx@tq4o$c)2&$eg5&ake*5yzx)jf@j')
# In production, ensure SECRET_KEY is set via environment variable
if IS_PRODUCTION and 'django-insecure-' in SECRET_KEY:
    raise ValueError("SECRET_KEY must be set via environment variable in production!")

# SECURITY WARNING: don't run with debug turned on in production!
# SECURITY: Debug mode should be False in production
DEBUG = get_env_bool('DEBUG', True)  # Default True for dev, set DEBUG=False in production

# SECURITY: ALLOWED_HOSTS configuration
# In production, only allow actual domain names
if IS_PRODUCTION:
    ALLOWED_HOSTS = ['chatbotad.io', 'www.chatbotad.io']
else:
    ALLOWED_HOSTS = [
        'localhost',
        '127.0.0.1',
        'chatbotad.io',
        'www.chatbotad.io',
        '18.232.180.166',
        '34.235.125.118',
        # ngrok domains (temporary - remove after testing)
        '.ngrok-free.app',
        '.ngrok-free.dev',
    ]

# Base URL for generating absolute links (booking pages, calendly redirects, etc.)
BASE_URL = 'https://chatbotad.io'

# SECURITY: Cookie and Session Settings
# In production, enable secure cookies
CSRF_COOKIE_SECURE = get_env_bool('CSRF_COOKIE_SECURE', not IS_PRODUCTION)
SESSION_COOKIE_SECURE = get_env_bool('SESSION_COOKIE_SECURE', not IS_PRODUCTION)

# Session expiry: 8 hours (28800 seconds)
SESSION_COOKIE_AGE = 28800
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_SAVE_EVERY_REQUEST = True  # Reset timer on every request

# Proxy settings for nginx reverse proxy
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

# CSRF trusted origins
CSRF_TRUSTED_ORIGINS = [
    'https://chatbotad.io',
    'http://chatbotad.io',
    'https://www.chatbotad.io',
    'http://www.chatbotad.io',
    'http://18.232.180.166',
    'https://18.232.180.166',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'newapp'
]

# Authentication backends
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'newapp.middleware.organization_middleware.OrganizationMiddleware',  # Multi-tenant context
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'newapp.middleware.authcheck.AdminAuthMiddleware'
]

ROOT_URLCONF = 'mynewsite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'newapp' / 'templates',
            BASE_DIR / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'newapp.context_processors.feature_flags',
            ],
        },
    },
]

WSGI_APPLICATION = 'mynewsite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
import os
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# STATICFILES_DIRS = []

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# PUBLIC_PATHS = [
#     "/appointment_date/",
#     "/create-event/",
# ]

# LOGIN_URL = "/login_view/"

# Celery Configuration with Local Redis
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'



# =============================================================================
# LOGGING CONFIGURATION (Low overhead)
# =============================================================================
LOG_DIR = BASE_DIR / 'logs'
LOG_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '%(asctime)s [%(levelname)s] %(name)s: %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'simple': {
            'format': '%(levelname)s %(message)s',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'chatbot.log',
            'maxBytes': 5 * 1024 * 1024,  # 5MB max
            'backupCount': 3,
            'formatter': 'standard',
        },
        'console': {
            'level': 'WARNING',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
        'newapp': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'webhook': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['file', 'console'],
        'level': 'INFO',
    },
}

MEDIA_ROOT = BASE_DIR / 'media'

# =============================================================================
# RATE LIMITING (Optional - uncomment if needed)
# =============================================================================
# To enable rate limiting, install: pip install django-ratelimit
# Then add @ratelimit decorator to views:
# from django_ratelimit.decorators import ratelimit
#
# @ratelimit(key='ip', rate='100/h')
# def my_view(request):
#     ...
# =============================================================================

MEDIA_URL = '/media/'


# =============================================================================
# ERROR MONITORING (Optional - uncomment to enable)
# =============================================================================
# To enable error monitoring with Sentry:
# 1. Install: pip install sentry-sdk
# 2. Uncomment the configuration below
# 3. Set your SENTRY_DSN environment variable
#
# SENTRY_DSN = os.environ.get('SENTRY_DSN', '')
# if SENTRY_DSN:
#     import sentry_sdk
#     sentry_sdk.init(
#         dsn=SENTRY_DSN,
#         traces_sample_rate=0.1,  # Set to 1.0 to trace all requests (impacts performance)
#         profiles_sample_rate=0.1,
#         environment='production' if IS_PRODUCTION else 'development',
#     )
# =============================================================================
