# Generated by Django 4.2 on 2025-12-08 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.TextField()),
                ('password', models.TextField()),
                ('whatsapp_phone_id', models.TextField()),
                ('whatsapp_token', models.TextField()),
                ('pinecone_token', models.TextField()),
                ('assistant_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('display_phone_no', models.TextField()),
                ('goolgle_calendar', models.TextField()),
                ('openai_api_key', models.TextField(blank=True, null=True)),
                ('chatgpt_mode', models.CharField(choices=[('prompt', 'Prompt'), ('ai_agent', 'AI Agent')], default='prompt', max_length=20)),
            ],
            options={
                'db_table': 'admins',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ChatGPTPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_text', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField()),
                ('is_escalation', models.BooleanField(default=False)),
                ('admin_id', models.ForeignKey(db_column='admin_id', on_delete=django.db.models.deletion.DO_NOTHING, to='newapp.admin')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('messages', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('who', models.CharField(choices=[('user', 'User'), ('bot', 'Bot')], max_length=10)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to='newapp.user')),
            ],
            options={
                'db_table': 'conversations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AIAgentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='ai_agent_pdfs/')),
                ('instruction', models.TextField(blank=True)),
                ('pdf_text', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.admin')),
            ],
            options={
                'db_table': 'ai_agent_config',
            },
        ),
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.ForeignKey(db_column='tag_id', on_delete=django.db.models.deletion.CASCADE, to='newapp.tag')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='newapp.user')),
            ],
            options={
                'db_table': 'user_tags',
                'unique_together': {('user', 'tag')},
            },
        ),
    ]
