# Generated by Django 4.2 on 2025-12-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followup_count',
            field=models.IntegerField(default=0),
        ),
    ]
