# Generated by Django 4.2 on 2025-12-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_user_followup_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='calendly_scheduling_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='calendly_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='followup_delay_minutes',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='admin',
            name='followup_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
