# Generated by Django 4.2 on 2025-12-26 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_admin_calendly_scheduling_url_admin_calendly_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalAPI',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the function for the AI to call (e.g., check_booking)', max_length=100)),
                ('description', models.TextField(help_text='Description for the AI explaining when to use this tool')),
                ('url', models.URLField(max_length=500)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], default='POST', max_length=10)),
                ('headers', models.JSONField(blank=True, default=dict, help_text='JSON headers')),
                ('payload', models.JSONField(blank=True, default=dict, help_text='JSON payload with {{placeholders}}')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.admin')),
            ],
            options={
                'db_table': 'external_apis',
            },
        ),
    ]
