# Generated by Django 4.2 on 2025-12-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_externalapi'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalapi',
            name='body_type',
            field=models.CharField(choices=[('json', 'JSON'), ('form', 'Form-encoded'), ('none', 'No Body')], default='json', max_length=20),
        ),
        migrations.AddField(
            model_name='externalapi',
            name='response_mapping',
            field=models.JSONField(blank=True, default=list, help_text='List of {jsonpath, custom_field} mappings'),
        ),
        migrations.AlterField(
            model_name='externalapi',
            name='method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], default='POST', max_length=10),
        ),
    ]
