# Generated by Django 4.2 on 2025-12-29 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_externalapi_body_type_externalapi_response_mapping_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAsset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Unique name to reference this image (e.g., menu_card)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description for the AI explaining when to use this image')),
                ('image', models.ImageField(upload_to='image_assets/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.admin')),
            ],
            options={
                'db_table': 'image_assets',
                'unique_together': {('admin', 'name')},
            },
        ),
    ]
