# Generated by Django 4.2 on 2026-01-02 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0006_imageasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='newapp.admin'),
        ),
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True, help_text='Description for the AI explaining when to apply this tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('admin', 'name')},
        ),
        migrations.CreateModel(
            name='FollowUpMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('step', models.IntegerField(help_text='Step number (1-4)')),
                ('delay_minutes', models.IntegerField(default=10, help_text='Delay in minutes before sending this follow-up')),
                ('message', models.TextField(help_text='The follow-up message content')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_messages', to='newapp.admin')),
            ],
            options={
                'db_table': 'followup_messages',
                'ordering': ['step'],
                'unique_together': {('admin', 'step')},
            },
        ),
    ]
