# Generated by Django 4.2 on 2026-01-02 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0007_tag_admin_tag_description_alter_tag_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('field_type', models.CharField(default='text', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.admin')),
            ],
            options={
                'db_table': 'custom_fields',
                'unique_together': {('admin', 'name')},
            },
        ),
        migrations.AddField(
            model_name='followupmessage',
            name='tag',
            field=models.ForeignKey(blank=True, help_text='Only send to users with this tag (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='newapp.tag'),
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.customfield')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.user')),
            ],
            options={
                'db_table': 'custom_field_values',
                'unique_together': {('custom_field', 'user')},
            },
        ),
    ]
