# Generated by Django 4.2 on 2026-01-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0008_customfield_followupmessage_tag_customfieldvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='source',
            field=models.CharField(default='Whatsapp', max_length=50),
        ),
    ]
