# Generated by Django 4.2 on 2026-01-08 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newapp', '0009_user_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('whatsapp_phone_id', models.TextField(blank=True, default='')),
                ('whatsapp_token', models.TextField(blank=True, default='')),
                ('display_phone_no', models.TextField(blank=True, default='')),
                ('openai_api_key', models.TextField(blank=True, null=True)),
                ('assistant_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('chatgpt_mode', models.CharField(choices=[('prompt', 'Prompt'), ('ai_agent', 'AI Agent')], default='prompt', max_length=20)),
                ('pinecone_token', models.TextField(blank=True, default='')),
                ('calendly_token', models.TextField(blank=True, null=True)),
                ('calendly_scheduling_url', models.TextField(blank=True, null=True)),
                ('followup_delay_minutes', models.IntegerField(default=10)),
                ('followup_enabled', models.BooleanField(default=True)),
                ('google_calendar', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('super_admin', 'Super Admin'), ('client_admin', 'Client Admin'), ('agent', 'Agent'), ('viewer', 'Viewer')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('can_manage_organizations', models.BooleanField(default=False)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('can_manage_settings', models.BooleanField(default=False)),
                ('can_view_inbox', models.BooleanField(default=True)),
                ('can_send_messages', models.BooleanField(default=True)),
                ('can_manage_tags', models.BooleanField(default=False)),
                ('can_manage_ai', models.BooleanField(default=False)),
                ('can_manage_contacts', models.BooleanField(default=True)),
                ('can_broadcast', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='admin_id',
            field=models.ForeignKey(blank=True, db_column='admin_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newapp.admin'),
        ),
        migrations.CreateModel(
            name='OrganizationUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='newapp.organization')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='newapp.role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='org_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'organization_users',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='organization_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='newapp.organization'),
        ),
    ]
