# Generated by Django 4.2 on 2026-01-23 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0010_add_multitenancy_models'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='externalapi',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_apis', to='newapp.organization'),
        ),
        migrations.AddField(
            model_name='tag',
            name='auto_apply',
            field=models.BooleanField(default=False, help_text='If True, tag is auto-applied when keyword matches user input'),
        ),
        migrations.AddField(
            model_name='tag',
            name='keyword',
            field=models.CharField(blank=True, help_text="Keyword that triggers this tag when user types it (e.g., 'STOP')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='newapp.organization'),
        ),
        migrations.AlterField(
            model_name='externalapi',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newapp.admin'),
        ),
    ]
