# Generated by Django 4.2 on 2026-01-28 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0011_add_organization_to_externalapi'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgptprompt',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newapp.admin'),
        ),
        migrations.AddField(
            model_name='chatgptprompt',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newapp.organization'),
        ),
        migrations.AlterModelTable(
            name='chatgptprompt',
            table='chatgpt_prompts',
        ),
    ]
