# Generated by Django 4.2 on 2026-01-28 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0012_add_org_admin_to_chatgptprompt'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='imageasset',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='imageasset',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newapp.organization'),
        ),
        migrations.AlterField(
            model_name='imageasset',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newapp.admin'),
        ),
    ]
