# Generated by Django 4.2 on 2026-01-30 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0013_alter_imageasset_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bot_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
