# Generated by Django 4.2 on 2026-02-02 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0014_user_bot_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastJob',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Optional campaign name', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_recipients', models.IntegerField(default=0)),
                ('sent_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('template_variables', models.JSONField(blank=True, default=dict, help_text='Variables for template placeholders')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newapp.admin')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newapp.organization')),
                ('tag', models.ForeignKey(blank=True, help_text='Send to users with this tag', null=True, on_delete=django.db.models.deletion.SET_NULL, to='newapp.tag')),
            ],
            options={
                'db_table': 'broadcast_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_in_inbox',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('template_id', models.CharField(help_text="Meta's template ID", max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('language', models.CharField(default='en_US', max_length=10)),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('category', models.CharField(choices=[('MARKETING', 'Marketing'), ('UTILITY', 'Utility'), ('AUTHENTICATION', 'Authentication')], default='MARKETING', max_length=50)),
                ('components', models.JSONField(default=list, help_text='Template components (header, body, buttons)')),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newapp.admin')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newapp.organization')),
            ],
            options={
                'db_table': 'whatsapp_templates',
                'unique_together': {('admin', 'organization', 'template_id')},
            },
        ),
        migrations.CreateModel(
            name='ScheduledFollowUp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('step', models.IntegerField(default=1, help_text='Follow-up step (1-4)')),
                ('scheduled_for', models.DateTimeField(db_index=True, help_text='When to send this follow-up')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('message', models.TextField(help_text='The follow-up message content')),
                ('attempts', models.IntegerField(default=0, help_text='Number of send attempts')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newapp.admin')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newapp.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_followups', to='newapp.user')),
            ],
            options={
                'db_table': 'scheduled_followups',
                'ordering': ['scheduled_for'],
            },
        ),
        migrations.CreateModel(
            name='BroadcastMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('meta_message_id', models.CharField(blank=True, help_text='Message ID from Meta API', max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('broadcast_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='newapp.broadcastjob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.user')),
            ],
            options={
                'db_table': 'broadcast_messages',
            },
        ),
        migrations.AddField(
            model_name='broadcastjob',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='newapp.whatsapptemplate'),
        ),
        migrations.AddIndex(
            model_name='scheduledfollowup',
            index=models.Index(fields=['status', 'scheduled_for'], name='scheduled_f_status_90bd2d_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcastmessage',
            index=models.Index(fields=['broadcast_job', 'status'], name='broadcast_m_broadca_35b70c_idx'),
        ),
    ]
