# Generated by Django 4.2 on 2026-02-04 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0016_update_customfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('log_type', models.CharField(choices=[('message_failed', 'Message Failed'), ('api_error', 'API Error'), ('custom_field_update', 'Custom Field Update'), ('window_closed', 'Window Closed'), ('bot_toggle', 'Bot Toggle'), ('tag_update', 'Tag Update'), ('system', 'System')], default='info', max_length=50)),
                ('level', models.CharField(choices=[('error', 'Error'), ('warning', 'Warning'), ('info', 'Info'), ('success', 'Success')], default='info', max_length=20)),
                ('message', models.TextField(help_text='The log message/details')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional JSON metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'user_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='customfieldvalue',
            new_name='custom_fiel_user_id_f53c49_idx',
            old_name='custom_field_user_idx',
        ),
        migrations.AlterUniqueTogether(
            name='customfield',
            unique_together={('admin', 'name')},
        ),
        migrations.AddField(
            model_name='organization',
            name='waba_id',
            field=models.TextField(blank=True, default='', help_text='WhatsApp Business Account ID'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Long Text'), ('number', 'Number'), ('email', 'Email'), ('phone', 'Phone'), ('date', 'Date'), ('datetime', 'DateTime'), ('boolean', 'Yes/No'), ('select', 'Dropdown')], default='text', help_text='Data type for this field', max_length=20),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='name',
            field=models.CharField(help_text='Field name (e.g., name, email, address)', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='customfield',
            unique_together={('organization', 'name'), ('admin', 'name')},
        ),
        migrations.AddField(
            model_name='userlog',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_logs', to='newapp.admin'),
        ),
        migrations.AddField(
            model_name='userlog',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_logs', to='newapp.organization'),
        ),
        migrations.AddField(
            model_name='userlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='newapp.user'),
        ),
        migrations.AddIndex(
            model_name='userlog',
            index=models.Index(fields=['user', 'created_at'], name='user_logs_user_id_bb3cbe_idx'),
        ),
        migrations.AddIndex(
            model_name='userlog',
            index=models.Index(fields=['log_type', 'created_at'], name='user_logs_log_typ_c7b13d_idx'),
        ),
    ]
