# Generated by Django 4.2 on 2026-03-06 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0018_webchat_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='webchatmessage',
            new_name='webchat_mes_session_75d80b_idx',
            old_name='webchat_msg_session_idx',
        ),
        migrations.RenameIndex(
            model_name='webchatmessage',
            new_name='webchat_mes_sender_b9d06f_idx',
            old_name='webchat_msg_sender_idx',
        ),
        migrations.RenameIndex(
            model_name='webchatsession',
            new_name='webchat_ses_session_890175_idx',
            old_name='webchat_sess_session_idx',
        ),
        migrations.RenameIndex(
            model_name='webchatsession',
            new_name='webchat_ses_status_2d7fb7_idx',
            old_name='webchat_sess_status_idx',
        ),
        migrations.RenameIndex(
            model_name='webchatsession',
            new_name='webchat_ses_user_id_61b2f8_idx',
            old_name='webchat_sess_user_idx',
        ),
        migrations.AddField(
            model_name='organization',
            name='app_version',
            field=models.CharField(choices=[('stable', 'Stable'), ('beta', 'Beta'), ('canary', 'Canary')], default='stable', help_text='Which version of features this org uses', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='gpt_model',
            field=models.CharField(default='gpt-4o-mini', max_length=50),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_beta_tester',
            field=models.BooleanField(default=False, help_text='If True, this org sees new features before general rollout'),
        ),
        migrations.AlterField(
            model_name='scheduledfollowup',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('sent', 'Sent'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='webchatanalytics',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='webchatmessage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='webchatsession',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='webchatwidget',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['created_at'], name='conversatio_created_694913_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['user_id'], name='conversatio_user_id_0d3af7_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['keyword'], name='tags_keyword_fa161e_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['organization_id'], name='tags_organiz_38f7d5_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['admin_id'], name='tags_admin_i_5ab927_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['organization_id'], name='users_organiz_ca9165_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['admin_id'], name='users_admin_i_98f2d7_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_in_inbox'], name='users_is_in_i_257a06_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_no'], name='users_phone_n_b44fe5_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='users_created_6541e9_idx'),
        ),
    ]
