# Generated by Django 4.2 on 2026-03-06 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0019_rename_webchat_msg_session_idx_webchat_mes_session_75d80b_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('opportunity_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('won', 'Won'), ('lost', 'Lost'), ('abandoned', 'Abandoned')], default='open', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_by', models.CharField(default='Manual', max_length=100)),
                ('moved_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'opportunities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pipelines',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='aiagentconfig',
            name='is_default',
            field=models.BooleanField(default=False, help_text='If true, this agent is used for incoming messages'),
        ),
        migrations.AddField(
            model_name='aiagentconfig',
            name='name',
            field=models.CharField(default='Default Agent', help_text='Agent name (e.g. Sales Agent, Support Agent)', max_length=100),
        ),
        migrations.AddField(
            model_name='aiagentconfig',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newapp.organization'),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, help_text='Custom logo for the topbar', null=True, upload_to='org_logos/'),
        ),
        migrations.AlterField(
            model_name='aiagentconfig',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newapp.admin'),
        ),
        migrations.CreateModel(
            name='PipelineStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('color', models.CharField(default='#3b82f6', help_text='Hex color for column header', max_length=7)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='newapp.pipeline')),
            ],
            options={
                'db_table': 'pipeline_stages',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='pipeline',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipelines', to='newapp.organization'),
        ),
        migrations.CreateModel(
            name='OpportunityComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='Admin', max_length=100)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='newapp.opportunity')),
            ],
            options={
                'db_table': 'opportunity_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='opportunity',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='newapp.organization'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='newapp.pipeline'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='newapp.pipelinestage'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='newapp.user'),
        ),
    ]
