# Generated by Django 4.2 on 2026-03-06 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0020_opportunity_pipeline_aiagentconfig_is_default_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineAutomation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('tag_applied', 'When tag is applied'), ('tag_removed', 'When tag is removed'), ('custom_field_changed', 'When custom field value changes')], max_length=30)),
                ('trigger_field_name', models.CharField(blank=True, default='', help_text='Custom field name to watch', max_length=100)),
                ('trigger_field_value', models.CharField(blank=True, default='', help_text='Value that triggers the move (empty = any change)', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automations', to='newapp.pipeline')),
                ('target_stage', models.ForeignKey(help_text='Move opportunity to this stage', on_delete=django.db.models.deletion.CASCADE, to='newapp.pipelinestage')),
                ('trigger_tag', models.ForeignKey(blank=True, help_text='Tag that triggers the automation', null=True, on_delete=django.db.models.deletion.CASCADE, to='newapp.tag')),
            ],
            options={
                'db_table': 'pipeline_automations',
            },
        ),
    ]
