# Generated by Django 4.2 on 2026-03-09 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0021_pipelineautomation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendlyLink',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Tag name used in prompt (e.g., quick_call)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description (e.g., 30 minute consultation)')),
                ('url', models.URLField(help_text='Calendly scheduling URL', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newapp.admin')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendly_links', to='newapp.organization')),
            ],
            options={
                'db_table': 'calendly_links',
            },
        ),
    ]
