# Generated by Django 4.2 on 2026-03-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0022_add_calendly_link_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendlylink',
            name='booking_message',
            field=models.TextField(blank=True, default='', help_text='Custom message to send when booking is confirmed'),
        ),
        migrations.AddField(
            model_name='calendlylink',
            name='custom_field_name',
            field=models.CharField(blank=True, default='', help_text='Custom field to update when booking is confirmed (e.g., appointment_status)', max_length=100),
        ),
    ]
