# Generated by Django 4.2 on 2026-03-10 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0023_add_calendly_link_booking_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendlyBookingTracker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('link_sent', 'Link Sent'), ('booked', 'Booked'), ('cancelled', 'Cancelled')], default='link_sent', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calendly_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='newapp.calendlylink')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendly_bookings', to='newapp.user')),
            ],
            options={
                'db_table': 'calendly_booking_tracker',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='calendlybookingtracker',
            index=models.Index(fields=['user', 'status'], name='calendly_bo_user_id_0168a9_idx'),
        ),
        migrations.AddIndex(
            model_name='calendlybookingtracker',
            index=models.Index(fields=['calendly_link', 'status'], name='calendly_bo_calendl_f9b024_idx'),
        ),
    ]
