# Generated by Django 4.2 on 2026-03-10 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0024_add_calendly_booking_tracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendlybookingtracker',
            name='booking_token',
            field=models.CharField(blank=True, help_text='UUID token for redirect-based booking tracking', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='contact_id',
            field=models.CharField(blank=True, help_text='Unique contact ID in SB-XXXX format', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='calendlybookingtracker',
            name='status',
            field=models.CharField(choices=[('link_sent', 'Link Sent'), ('clicked', 'Link Clicked'), ('booked', 'Booked'), ('cancelled', 'Cancelled')], default='link_sent', max_length=20),
        ),
        migrations.AddIndex(
            model_name='calendlybookingtracker',
            index=models.Index(fields=['booking_token'], name='calendly_bo_booking_22ad62_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['contact_id'], name='users_contact_4b95f7_idx'),
        ),
    ]
