# Generated by Django 4.2 on 2026-04-20 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0026_multi_prompt_template_pipeline_api_chain'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='hide_logo',
            field=models.BooleanField(default=False, help_text='If True, hides the SpeedBots logo in the sidebar for this org'),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='terms_accepted',
            field=models.BooleanField(default=False, help_text='Whether user has accepted Terms & Conditions'),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, help_text='When T&C were accepted', null=True),
        ),
        migrations.CreateModel(
            name='GoogleCalendarLink',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Tag name used in prompt (e.g., consultation)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description (e.g., 30 minute consultation)')),
                ('calendar_id', models.CharField(help_text='Google Calendar ID (e.g., primary or abc@group.calendar.google.com)', max_length=300)),
                ('duration_minutes', models.IntegerField(default=30, help_text='Appointment duration in minutes')),
                ('service_account_json', models.TextField(blank=True, default='', help_text='Google service account JSON credentials')),
                ('custom_field_name', models.CharField(blank=True, default='', help_text='Custom field to update when booking is confirmed', max_length=100)),
                ('booking_message', models.TextField(blank=True, default='', help_text='Custom message to send when booking is confirmed')),
                ('available_days', models.JSONField(blank=True, default=list, help_text='Days available [0=Mon..6=Sun], empty=all')),
                ('start_hour', models.IntegerField(default=9, help_text='Earliest bookable hour (24h format)')),
                ('end_hour', models.IntegerField(default=17, help_text='Latest bookable hour (24h format)')),
                ('timezone', models.CharField(default='Asia/Kuala_Lumpur', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newapp.admin')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gcalendar_links', to='newapp.organization')),
            ],
            options={
                'db_table': 'google_calendar_links',
            },
        ),
        migrations.CreateModel(
            name='GoogleCalendarBooking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_token', models.CharField(help_text='UUID token for booking page URL', max_length=64, unique=True)),
                ('status', models.CharField(choices=[('link_sent', 'Link Sent'), ('slot_selected', 'Slot Selected'), ('booked', 'Booked'), ('cancelled', 'Cancelled')], default='link_sent', max_length=20)),
                ('selected_slot', models.DateTimeField(blank=True, help_text='Selected appointment time', null=True)),
                ('google_event_id', models.CharField(blank=True, default='', help_text='Google Calendar event ID', max_length=200)),
                ('attendee_name', models.CharField(blank=True, default='', max_length=200)),
                ('attendee_email', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gcalendar_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='newapp.googlecalendarlink')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gcalendar_bookings', to='newapp.user')),
            ],
            options={
                'db_table': 'google_calendar_bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='googlecalendarbooking',
            index=models.Index(fields=['booking_token'], name='google_cale_booking_5ed06b_idx'),
        ),
        migrations.AddIndex(
            model_name='googlecalendarbooking',
            index=models.Index(fields=['user', 'status'], name='google_cale_user_id_0de2b5_idx'),
        ),
    ]
